from __future__ import annotations
import typing


class DbConnection(typing.Protocol):
    def execute(self, query, values=None) -> DbConnection: ...

    def fetchall(self) -> typing.List[typing.Any]: ...

    def fetchone(self) -> typing.Any: ...

    def fetchval(self, pos: int) -> typing.Any: ...
